name: Build Javadoc

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build JavaDoc
        uses: AmarokIce/AmarokJsonForJava@1.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 8
          target-folder: javadoc
          project: gradle
