name: Javadoc

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  apidoc-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Generate docs
        run: mvn javadoc:javadoc

      - name: Copy to Location
        run: |
          rm -rf docs
          mkdir -vp docs
          cp -vrf build/docs/javadoc/

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://carmjos.github.io/userprefix
          path-to-root: docs

      - name: Configure Git
        env:
          DEPLOY_PRI: ${{secrets.DEPLOY_PRI}}
          GIT_USERNAME: ${{ github.repository_owner }}
          GIT_EMAIL: snowlyicewolf@outlook.com
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name '$DEPLOY_PRI'
          git config --global user.email '$DEPLOY_PRI'


      - name: Commit documentation
        env:
          GIT_URL: "git@github.com:AmarokIce/AmarokJsonForJava.git"
        run: |
          cd docs
          git init
          git remote add origin $GIT_URL
          git checkout -b gh-pages
          git add -A
          git commit -m "API Document generated."

      - name: Push javadocs # 推送
        run: |
          cd docs
          git push origin HEAD:gh-pages --force

